<a href="https://colab.research.google.com/github/VernonNaidoo-Toronto/3253_ML_Final_Project_Candidates/blob/master/VN_COVID_19_Dataset_Group_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Analysis of Dataset Group #1: COVID-19 
1. covid_19_data.csv
1. COVID19_line_list_data.csv
1. COVID19_open_line_list.csv
1. time_series_covid_19_confirmed_US.csv
1. time_series_covid_19_confirmed.csv
1. time_series_covid_19_deaths.csv
1. time_series_covid_10_recovered.csv

## Setup

In [ ]:
# Import libraries
import pandas as pd
import numpy as np

In [ ]:
path = 'https://raw.githubusercontent.com/VernonNaidoo-Toronto/3253_ML_Final_Project_Candidates/master/COVID-19_Dataset_1/'

## 1. covid_19_data

In [ ]:
covid_19_data = pd.read_csv(path+'covid_19_data.csv')
covid_19_data

         SNo ObservationDate     Province/State  ... Confirmed  Deaths  Recovered
0          1      01/22/2020              Anhui  ...       1.0     0.0        0.0
1          2      01/22/2020            Beijing  ...      14.0     0.0        0.0
2          3      01/22/2020          Chongqing  ...       6.0     0.0        0.0
3          4      01/22/2020             Fujian  ...       1.0     0.0        0.0
4          5      01/22/2020              Gansu  ...       0.0     0.0        0.0
...      ...             ...                ...  ...       ...     ...        ...
68553  68554      07/20/2020  Zaporizhia Oblast  ...     678.0    20.0      551.0
68554  68555      07/20/2020            Zeeland  ...     791.0    69.0        0.0
68555  68556      07/20/2020           Zhejiang  ...    1270.0     1.0     1267.0
68556  68557      07/20/2020    Zhytomyr Oblast  ...    1602.0    34.0     1251.0
68557  68558      07/20/2020       Zuid-Holland  ...   11886.0  1305.0        0.0

[68558 rows x 8 columns]

## 2. COVID19_line_list_data

In [ ]:
COVID19_line_list_data = pd.read_csv(path+'COVID19_line_list_data.csv')
COVID19_line_list_data

## 3. COVID19_open_line_list

In [ ]:
COVID19_open_line_list = pd.read_csv(path+'COVID19_open_line_list.csv')
COVID19_open_line_list

        ID  age     sex  ... Unnamed: 42 Unnamed: 43 Unnamed: 44
0      1.0   30    male  ...         NaN         NaN         NaN
1      2.0   47    male  ...         NaN         NaN         NaN
2      3.0   49    male  ...         NaN         NaN         NaN
3      4.0   47  female  ...         NaN         NaN         NaN
4      5.0   50  female  ...         NaN         NaN         NaN
...    ...  ...     ...  ...         ...         ...         ...
14121  NaN  NaN     NaN  ...         NaN         NaN         NaN
14122  NaN  NaN     NaN  ...         NaN         NaN         NaN
14123  NaN  NaN     NaN  ...         NaN         NaN         NaN
14124  NaN  NaN     NaN  ...         NaN         NaN         NaN
14125  NaN  NaN     NaN  ...         NaN         NaN         NaN

[14126 rows x 45 columns]

## 4. time_series_covid_19_confirmed_US

In [ ]:
time_series_covid_19_confirmed_US = pd.read_csv(path+'time_series_covid_19_confirmed_US.csv')
time_series_covid_19_confirmed_US

           UID iso2 iso3  code3  ...  7/17/20 7/18/20 7/19/20 7/20/20
0           16   AS  ASM     16  ...        0       0       0       0
1          316   GU  GUM    316  ...      314     314     314     319
2          580   MP  MNP    580  ...       37      37      37      38
3     63072001   PR  PRI    630  ...       67      68      72      72
4     63072003   PR  PRI    630  ...       66      67      70      71
...        ...  ...  ...    ...  ...      ...     ...     ...     ...
3335  84070016   US  USA    840  ...      295     301     306     306
3336  84070017   US  USA    840  ...       55      56      58      60
3337  84070018   US  USA    840  ...     2317    2369    2437    2497
3338  84070019   US  USA    840  ...       90     101     103     109
3339  84070020   US  USA    840  ...     1928    2005    2054    2071

[3340 rows x 192 columns]

## 5. time_series_covid_19_confirmed

In [ ]:
time_series_covid_19_confirmed = pd.read_csv(path+'time_series_covid_19_confirmed.csv')
time_series_covid_19_confirmed

    Province/State         Country/Region        Lat  ...  7/18/20  7/19/20  7/20/20
0              NaN            Afghanistan  33.939110  ...    35301    35475    35526
1              NaN                Albania  41.153300  ...     4008     4090     4171
2              NaN                Algeria  28.033900  ...    22549    23084    23691
3              NaN                Andorra  42.506300  ...      880      880      884
4              NaN                 Angola -11.202700  ...      687      705      749
..             ...                    ...        ...  ...      ...      ...      ...
261            NaN  Sao Tome and Principe   0.186400  ...      743      746      746
262            NaN                  Yemen  15.552727  ...     1581     1606     1619
263            NaN                Comoros -11.645500  ...      328      334      334
264            NaN             Tajikistan  38.861000  ...     6834     6878     6921
265            NaN                Lesotho -29.610000  ...      359      359      359

[266 rows x 185 columns]

## 6. time_series_covid_19_deaths

In [ ]:
time_series_covid_19_deaths = pd.read_csv(path+'time_series_covid_19_deaths.csv')
time_series_covid_19_deaths

    Province/State         Country/Region        Lat  ...  7/18/20  7/19/20  7/20/20
0              NaN            Afghanistan  33.939110  ...     1164     1181     1185
1              NaN                Albania  41.153300  ...      111      112      113
2              NaN                Algeria  28.033900  ...     1068     1078     1087
3              NaN                Andorra  42.506300  ...       52       52       52
4              NaN                 Angola -11.202700  ...       29       29       29
..             ...                    ...        ...  ...      ...      ...      ...
261            NaN  Sao Tome and Principe   0.186400  ...       14       14       14
262            NaN                  Yemen  15.552727  ...      443      445      447
263            NaN                Comoros -11.645500  ...        7        7        7
264            NaN             Tajikistan  38.861000  ...       57       57       57
265            NaN                Lesotho -29.610000  ...        6        6        6

[266 rows x 185 columns]

## 7. time_series_covid_19_recovered

In [ ]:
time_series_covid_19_recovered = pd.read_csv(path+'time_series_covid_19_recovered.csv')
time_series_covid_19_recovered

    Province/State         Country/Region        Lat  ...  7/18/20  7/19/20  7/20/20
0              NaN            Afghanistan  33.939110  ...    23273    23634    23741
1              NaN                Albania  41.153300  ...     2264     2311     2352
2              NaN                Algeria  28.033900  ...    15744    16051    16400
3              NaN                Andorra  42.506300  ...      803      803      803
4              NaN                 Angola -11.202700  ...      210      221      221
..             ...                    ...        ...  ...      ...      ...      ...
248            NaN  Sao Tome and Principe   0.186400  ...      337      451      536
249            NaN                  Yemen  15.552727  ...      701      712      714
250            NaN                Comoros -11.645500  ...      311      313      313
251            NaN             Tajikistan  38.861000  ...     5529     5578     5629
252            NaN                Lesotho -29.610000  ...       69       69       69

[253 rows x 185 columns]